### ISSUE TITLE
Only Hodir issues.

### ISSUE THREAD

**Issue by Ulduar** [scriptdev2/scriptdev2-cata#10]
https://github.com/scriptdev2/scriptdev2-cata/blob/master/scripts/northrend/ulduar/ulduar/boss_hodir.cpp
Maybe I'm repeating myself, but still.
1) Despite the addition of Attack Start return if m_bEventFinished = true.
Attack he can not, but aggro instance data changes due hodir helper npc.
They do not care about 35 fractions. They just attack flash freeze, which as you know the attack on him boss enters into battle, instance data changes, the doors close and the script breaks.
Solution was suggested headache - you said that you will not be added. Okay.
As far as I've seen on the official server, flash freeze should immediately go into despawned (some visual effect they have)
``` CPP
NPC_DRUID_HORDE_N           = 32941,                    // Tor Greycloud
    NPC_DRUID_HORDE_H           = 33333,                    // Kar Greycloud
    NPC_SHAMAN_HORDE_N          = 32950,                    // Spiritwalker Yona
    NPC_SHAMAN_HORDE_H          = 33332,                    // Spiritwalker Tara
    NPC_MAGE_HORDE_N            = 32946,                    // Veesha Blazeweaver
    NPC_MAGE_HORDE_H            = 33331,                    // Amira Blazeweaver
    NPC_PRIEST_HORDE_N          = 32948,                    // Battle-Priest Eliza
    NPC_PRIEST_HORDE_H          = 33330,                    // Battle-Priest Gina
    NPC_DRUID_ALLIANCE_N        = 32901,                    // Ellie Nightfeather
    NPC_DRUID_ALLIANCE_H        = 33325,                    // Eivi Nightfeather
    NPC_SHAMAN_ALLIANCE_N       = 32900,                    // Elementalist Avuun
    NPC_SHAMAN_ALLIANCE_H       = 33328,                    // Elementalist Mahfuun
    NPC_MAGE_ALLIANCE_N         = 32893,                    // Missy Flamecuffs
    NPC_MAGE_ALLIANCE_H         = 33327,                    // Sissy Flamecuffs
    NPC_PRIEST_ALLIANCE_N       = 32897,                    // Field Medic Penny
    NPC_PRIEST_ALLIANCE_H       = 33326,                    // Field Medic Jessi
    NPC_FLASH_FREEZE                    = 32926,                // entry used during the encounter
    NPC_FLASH_FREEZE_NPC                = 32938,                // entry which stuns the friendly npcs before the actual fight

```

It is necessary to assign them guid list or something. Flash Freeze too.
 Also go into despawned, but not immediately. They rejoice in the release of Hodir and 30 seconds despawned.
When evade Hodir (if m_bEventFinished ! = True)
And Hodir Helper and Flash Freeze must despawned as Hodir himself. Instance script then resummon them.

**Comment by xfurry** [comment]
I still can't find any problem with this script.
Please make sure that you are testing this with a complete party using the latest versions of core, SD2 and DB.

**Comment by Ulduar** [comment]
``` CPP
else if (uiEventId == EVENT_ID_ATTACK_START)
        {
            // Start encounter
            if (m_bEventFinished)
                return;

            if (Creature* pHodir = pInstance->GetSingleCreatureFromStorage(NPC_HODIR))
                pHodir->SetInCombatWithZone();
        }

        return true;
```
And here the database or the core. 
                pHodir->SetInCombatWithZone();
Please be the boss to 1 percent xn, he becomes friendly, hit the ice and all the flash it again in battle. A Hodir helper ignore fraction killing lump again they are being attacked. Instance data changes, the doors are closed and all - the script bungle.

**Comment by xfurry** [comment]
Ok, now I think I understand what are you trying to say.
I will check again.

**Comment by xfurry** [comment]
I hope this will do the job https://github.com/scriptdev2/scriptdev2/commit/db23c6e41d84b0f4a51bda1ddc59efd483935fe3
