### ISSUE TITLE
Algalon the Observer bugs)

### ISSUE THREAD

**Issue by Ulduar** [scriptdev2/scriptdev2-cata#20]
https://github.com/scriptdev2/scriptdev2-cata/blob/master/scripts/northrend/ulduar/ulduar/boss_algalon.cpp
1) When aggro (the very first time) must have a delay before the attack and set itself UNIT_FLAGS_NOT_SELECTABLE, and when finished speaking case SAY_ENGAGE:
Must begin to attack. The second time he begins to attack after you've finished talking SAY_AGGRO.
2) http://www.wowhead.com/achievement=3036/observed-10-player and http://www.wowhead.com/achievement=3037/observed-25-player
Handled missing - need complete please)
``` CPP     
SPELL_KILL_CREDIT                   = 65184,                // achiev check spell
```
Will not work in this case,
3)
``` CPP
static const DialogueEntry aAlgalonDialogue[] =
{
    {SAY_INTRO_1,           NPC_ALGALON,        6000},
    {SPELL_SUMMON_AZEROTH,  0,                  5000},
    {SAY_INTRO_2,           NPC_ALGALON,        8000},
    {SAY_INTRO_3,           NPC_ALGALON,        0},
    {SAY_AGGRO,             NPC_ALGALON,        14000},
    {SAY_ENGAGE,            NPC_ALGALON,        0},
    {SPELL_ASCEND_HEAVENS,  0,                  3000},
    {SPELL_BERSERK,         0,                  0},
    {SAY_DESPAWN_1,         NPC_ALGALON,        15000},
    {SAY_DESPAWN_2,         NPC_ALGALON,        8000},
    {SAY_DESPAWN_3,         NPC_ALGALON,        10000},
    {SPELL_TELEPORT,        0,                  0},
    {NPC_ALGALON,           0,                  12000},
    {SAY_OUTRO_1,           NPC_ALGALON,        39000},
    {SAY_OUTRO_2,           NPC_ALGALON,        18000},
    {SAY_OUTRO_3,           NPC_ALGALON,        12000},
    {SAY_OUTRO_4,           NPC_ALGALON,        12000},
    {SAY_BRANN_OUTRO,       NPC_BRANN_ALGALON,  11000},
    {SAY_OUTRO_5,           NPC_ALGALON,        0},
    {0, 0, 0},
};
```
SPELL_TELEPORT Missing after SAY_OUTRO_5 - need add(Algalon should also teleport)
SPELL_ASCEND_HEAVENS - Did not see that he cast his honest after ALGALON_TIMER == FAIL. Why the then refuses to cast. Should cast.
SPELL_ASCEND_HEAVENS need add also after SAY_DESPAWN_3 maybe?
First castes then teleport
4)
``` CPP
void DoStartIntroEvent()
    {
        m_creature->SetLevitate(true);
        DoCastSpellIfCan(m_creature, SPELL_ARRIVAL, CAST_TRIGGERED);
        DoCastSpellIfCan(m_creature, SPELL_RIDE_LIGHTNING, CAST_TRIGGERED);
        m_creature->GetMotionMaster()->MovePoint(1, afAlgalonMovePos[0], afAlgalonMovePos[1], afAlgalonMovePos[2]);
    }
```
SPELL_ARRIVAL need delete no need CAST_TRIGGERED(spell refuse cast at has that flag)
5)
```CPP
void JustReachedHome() override
    {
        if (!m_pInstance)
            return;

        if (m_bEventFinished)
        {
            if (m_pInstance->GetData(TYPE_ALGALON) == DONE)
            {
                // complete the achiev and start outro dialogue
                DoCastSpellIfCan(m_creature, SPELL_KILL_CREDIT, CAST_TRIGGERED);
                DoCastSpellIfCan(m_creature, SPELL_SUPERMASSIVE_FAIL, CAST_TRIGGERED);
                StartNextDialogueText(NPC_ALGALON);
            }
            else
                StartNextDialogueText(SAY_DESPAWN_1);
```
StartNextDialogueText(SAY_DESPAWN_1);
Need add check on instance_data(if TYPE_ALGALON_TIMER = 0), Only then run despawn event.
Also on Cataclysm does not appear himself worldstate (I do  know what it was removed in 4.xx, but for me personally it does not interfere, but the timer is not displayed on the screen) - I ask you not to remove worldstate, it is still not visible)
``` CPP
void JustDidDialogueStep(int32 iEntry) override
    {
        if (!m_pInstance)
            return;

        switch (iEntry)
        {
            case SPELL_SUMMON_AZEROTH:
                DoCastSpellIfCan(m_creature, SPELL_SUMMON_AZEROTH, CAST_TRIGGERED);
                break;
            case SAY_INTRO_2:
                DoCastSpellIfCan(m_creature, SPELL_REORIGINATION);
                break;
            case SAY_ENGAGE:
                // summon Living Constellations at this point
                DoSpawnConstellations();
                break;
            case SPELL_BERSERK:
                EnterEvadeMode();
                break;
            case SPELL_TELEPORT:
                // despawn when time has run out
                DoCastSpellIfCan(m_creature, SPELL_TELEPORT, CAST_TRIGGERED);
                m_creature->ForcedDespawn(2000);
                break;
            case NPC_ALGALON:
                // spawn Brann for epilogue dialogue
                m_creature->SummonCreature(NPC_BRANN_ALGALON, 1631.962f, -208.6464f, 420.8867f, 4.71f, TEMPSUMMON_DEAD_DESPAWN, 0);
                break;
            case SAY_OUTRO_1:
                m_creature->SetStandState(UNIT_STAND_STATE_KNEEL);
                break;
        }
    }
```
SPELL_BERSERK need add in UpdateAI, missing
``` CPP
void UpdateAI(const uint32 uiDiff) override
    {
        DialogueUpdate(uiDiff);

        if (!m_creature->SelectHostileTarget() || !m_creature->getVictim())
            return;

        if (m_uiBerserkTimer)
        {
            if (m_uiBerserkTimer <= uiDiff)
            {
                // it's unclear wether it casts Berserk or Ascend to Heavens
                if (DoCastSpellIfCan(m_creature, SPELL_ASCEND_HEAVENS, CAST_INTERRUPT_PREVIOUS) == CAST_OK)
                {
                    DoScriptText(SAY_BERSERK, m_creature);
                    m_uiBerserkTimer = 0;
                }
            }
            else
                m_uiBerserkTimer -= uiDiff;
        }
```
Maybe DoScriptText replace on        StartNextDialogueText(SPELL_ASCEND_HEAVENS); and add in dialogue helper after SPELL_ASCEND?
Also if EnterEvadeMode, First, he casts a spell ASCEND_HEAVEN, only then Enter Evade Mode.
This is one of my favorite bosses)
http://www.wowhead.com/npc=33052/living-constellation
On Reset Should have FLAG_NOT_SELECTABLE(if RECEIVE_AI_EVENT or ActivateRandomConstellation - Remove Flags - maybe sniff info missing?)
That's it - thanks in advance)

**Comment by xfurry** [comment]
1. Please open ticket on SD2 master. You know that we always fix pre-Cata stuff on master.
2. Please break the ticket into individual issues. I don't like reading a wall of text....
3. When providing code, please provide a patch. I don't know exactly what you changed and it makes things much more easier.

**Comment by Ulduar** [comment]
Okay, but you at least that's the query to pull the look.
https://github.com/scriptdev2/scriptdev2-cata/pull/19
And the issue is specific to Cataclysm, not Wotlk.

**Comment by xfurry** [comment]
This looks good so far.
There is one thing which I'm not sure if we should use it:
```
t%s begins to cast |cFFFF0000|Hspell:98951|h[Splitting Blow]|h|r !
```
We didn't have this format in SD2 before, so I'm not sure what to say. Maybe ask @Schmoozerd

**Comment by Ulduar** [comment]
He said that he is not engaged in Cataclysm. This format is used in Cataclysm Blizzard, in order to make it clear link to spell and what it does on the screen.

**Comment by xfurry** [comment]
I am just asking about the format, because I haven't seen this before.
So I also need to test to check if this works as expected in this format.

**Comment by Ulduar** [comment]
take creature_ai_texts, insert back to some boss (Argalot example) and check

**Comment by Schmoozerd** [comment]
are you guys sure blizz sends this and not an addon?

**Comment by xfurry** [comment]
I'm not. However we use something similar for outdoor pvp in the core: https://github.com/cmangos/mangos-wotlk/blob/master/sql/mangos.sql#L4555
I know that @stfx added the prefix to the texts.

**Comment by Ulduar** [comment]
Yes it sends Blizzard. And seen (I played it without addons)

**Comment by Ulduar** [comment]
``` QUOTE
Please open ticket on SD2 master. You know that we always fix pre-Cata stuff on master.
```
I wonder why then Baradin Hold in Wotlk not running again? XDD

**Comment by stfx** [comment]
Pretty sure that messages for opvp came from sniffs so on retail custom formatting like @xfurry mentioned is definitely sent in some cases.
