### ISSUE TITLE
The Light of Dawn

### ISSUE THREAD

**Issue by Ulduar** [scriptdev2/scriptdev2-cata#22]
http://www.wowhead.com/quest=12801/the-light-of-dawn
The only problem in Cata 4.3.4.
``` CPP
WORLD_STATE_FORCES_SHOW             = 3592,             // show the remaining units
    WORLD_STATE_FORCES_SCOURGE          = 3591,
    WORLD_STATE_FORCES_LIGHT            = 3590,
    WORLD_STATE_BATTLE_TIMER_SHOW       = 3603,             // countdown timer
    WORLD_STATE_BATTLE_TIMER_TIME       = 3604,
    WORLD_STATE_BATTLE_BEGIN            = 3605,             // battle has begun
```
None of WorldState not displayed, all conditions are met. But do not want to show in any way.

**Comment by xfurry** [comment]
I think this is a core issue. If I'm not mistaken, I think that world states are not displayed at all in Cata due to missing opcode implementation or something similar.

**Comment by Ulduar** [comment]
you are mistaken
