### ISSUE TITLE
All Is Well That Ends Well(13631) and Heroic: All Is Well That Ends Well(13819)

### ISSUE THREAD

**Issue by ghost** [scriptdev2/scriptdev2-cata#3]
Good time of day! 
I tried partially scripted this interesting quest for sending the reply code Alpha Titans.
http://paste2.org/hc04NCOU
Faced with a problem.

``` SQL
SPELL_ALGALON_EVENT_BEAM         = 64367,                // puspose unk
    // SPELL_ALGALON_EVENT_CLIMAX       = 64580,

```

I do not know who is and who should be cast. There's an effect of darkening sky.
http://www.wowhead.com/quest=13631/all-is-well-that-ends-well
http://wowpedia.org/Quest:All_Is_Well_That_Ends_Well
http://www.wowwiki.com/Quest:All_Is_Well_That_Ends_Well
It is possible that the quest is better to implement in SD2, but this script can take the data points, text, and so on. Thanks in advance! Please see. 
PS: Not implemented nor Mangos or the Trinity!

**Comment by Ulduar** [comment]
You're early closed issue, the issue has not been resolved. No NPC triggers in the database. And not implemented their script, I offered even a hack, but the solution. Also respawtime Rhonin should change the script. But you do not want to read it.
http://cmangos.net/thread-6615-post-42512.html#pid42512
